version: '3.1'
services:
    # my-app:
    # image: marceloicampos/my-app:1.0
    # ports:
    # - 3000:3000
    mongodb:
        container_name: mongo
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pwd123
        volumes:
            - mongo_data:/data/db
    mongo-express:
        container_name: mongo_express
        image: mongo-express
        restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: 123456
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: pwd123
            ME_CONFIG_MONGODB_URL: mongodb://root:pwd123@mongodb:27017/
        depends_on:
            - mongodb
volumes:
    mongo_data:
        driver: local
